from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED_API_VERSION = "UNSUPPORTED_API_VERSION"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TENANT_SCOPE_MISMATCH = "TENANT_SCOPE_MISMATCH"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    FILE_RESOURCE_NOT_FOUND = "FILE_RESOURCE_NOT_FOUND"
    STREAM_SESSION_NOT_FOUND = "STREAM_SESSION_NOT_FOUND"
    PROCESSING_JOB_NOT_FOUND = "PROCESSING_JOB_NOT_FOUND"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    INVALID_OBJECT_NAME = "INVALID_OBJECT_NAME"
    ADAPTER_TIMEOUT = "ADAPTER_TIMEOUT"
    ADAPTER_UNAVAILABLE = "ADAPTER_UNAVAILABLE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
