from enum import StrEnum


class FileResourceStatus(StrEnum):
    PENDING_UPLOAD = "PENDING_UPLOAD"
    UPLOADING = "UPLOADING"
    VERIFYING = "VERIFYING"
    AVAILABLE = "AVAILABLE"
    PROCESSING = "PROCESSING"
    QUARANTINED = "QUARANTINED"
    DELETING = "DELETING"
    DELETED = "DELETED"
    FAILED = "FAILED"


class StreamSessionStatus(StrEnum):
    CREATING = "CREATING"
    READY = "READY"
    ACTIVE = "ACTIVE"
    DRAINING = "DRAINING"
    CLOSED = "CLOSED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class StreamProtocol(StrEnum):
    WEBRTC = "WEBRTC"
    RTMP = "RTMP"
    HLS = "HLS"
    WS_AUDIO = "WS_AUDIO"
    WS_VIDEO = "WS_VIDEO"
    WEBSOCKET = "WEBSOCKET"


class StreamConnectionState(StrEnum):
    DISCONNECTED = "DISCONNECTED"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"


class StreamEventType(StrEnum):
    STREAM_CREATED = "STREAM_CREATED"
    STREAM_CONNECTED = "STREAM_CONNECTED"
    STREAM_DISCONNECTED = "STREAM_DISCONNECTED"
    STREAM_TIMEOUT = "STREAM_TIMEOUT"
    STREAM_RESTART_REQUIRED = "STREAM_RESTART_REQUIRED"


class ProcessingJobStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class GrantStatus(StrEnum):
    ACTIVE = "ACTIVE"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
